#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

// Nomes que podem aparecer na plaquinha acima da caixa de dialogo.
//
// Tres arquivos precisam concordar, NA MESMA ORDEM:
//   1. este enum                      SP_NAME_LILLIE
//   2. src/data/speaker_names.h       o texto que aparece na tela
//   3. charmap.txt                    NAME_LILLIE, para escrever {SPEAKER NAME_LILLIE}
//
// Nao reordene nem remova entradas: o byte gravado no texto e o indice deste
// enum, entao mexer na ordem troca o nome de toda fala ja escrita. Sempre
// ACRESCENTE antes de SP_NAME_COUNT.
//
// Para adicionar um falante, use o ajudante da skill `nomear-falante`, que
// edita os tres arquivos de uma vez e confere o resultado:
//   python3 .claude/skills/nomear-falante/adicionar_falante.py PRYCE "Pryce"
//   python3 .claude/skills/nomear-falante/checar_falantes.py
// {SPEAKER NAME_X} grava o indice em SPEAKER_ARG_BYTES bytes (alto, baixo),
// cada um de 00 a FE: FF e o fim de texto e cortaria a fala. Indice =
// alto * 255 + baixo, o que da ate 255 * 255 = 65025 falantes. charmap.txt
// escreve NAME_X = 00 05; a skill `nomear-falante` gera esses valores.
#define SPEAKER_ARG_BYTES 2
#define SPEAKER_ARG_BASE  255
#define SPEAKER_MAX_NAMES (SPEAKER_ARG_BASE * SPEAKER_ARG_BASE)

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_LOOKER,
    SP_NAME_ANABEL,
    SP_NAME_LILLIE,
    SP_NAME_GLADION,
    SP_NAME_KUKUI,
    SP_NAME_PRYCE,
    SP_NAME_CLAIR,
    SP_NAME_OLD_MAN,
    SP_NAME_ELM,
    SP_NAME_LUSAMINE,
    SP_NAME_KURT,
    SP_NAME_HECTOR,
    SP_NAME_BOY,
    SP_NAME_NEIGHBOR,   // Gold or Crystal: the plaque is "{NEIGHBOR}", resolved per player gender
    SP_NAME_SAILOR,
    SP_NAME_COLRESS,
    SP_NAME_BRUNO,
    SP_NAME_ELESA,
    SP_NAME_VOLKNER,
    SP_NAME_STEVEN,
    SP_NAME_RAMOS,
    SP_NAME_GUZMA,
    SP_NAME_SOLIERA,
    SP_NAME_BYRON,
    SP_NAME_FANTINA,
    SP_NAME_OAK,
    SP_NAME_FLORIST,
    SP_NAME_ELDER,          // Dragon's Den Master (Clair's grandfather)
    SP_NAME_CHUCKS_WIFE,
    SP_NAME_OFFICER,        // generic police officer (Sun and Moon Altar)
    SP_NAME_AETHER,         // generic Aether Foundation staff (Sun and Moon Altar)
    SP_NAME_RED,
    SP_NAME_BLUE,
    SP_NAME_BROCK,
    SP_NAME_MISTY,
    SP_NAME_LT_SURGE,
    SP_NAME_ERIKA,
    SP_NAME_KOGA,
    SP_NAME_SABRINA,
    SP_NAME_BLAINE,
    SP_NAME_GIOVANNI,
    SP_NAME_LANCE,
    SP_NAME_ARCHER,
    SP_NAME_ARIANA,
    SP_NAME_PROTON,
    SP_NAME_PETREL,
    SP_NAME_SILVER,
    SP_NAME_FALKNER,
    SP_NAME_BUGSY,
    SP_NAME_WHITNEY,
    SP_NAME_MORTY,
    SP_NAME_CHUCK,
    SP_NAME_JASMINE,
    SP_NAME_WILL,
    SP_NAME_KAREN,
    SP_NAME_EUSINE,
    SP_NAME_BRENDAN,
    SP_NAME_MAY,
    SP_NAME_WALLY,
    SP_NAME_ROXANNE,
    SP_NAME_BRAWLY,
    SP_NAME_WATTSON,
    SP_NAME_FLANNERY,
    SP_NAME_NORMAN,
    SP_NAME_WINONA,
    SP_NAME_TATE_AND_LIZA,
    SP_NAME_WALLACE,
    SP_NAME_JUAN,
    SP_NAME_SIDNEY,
    SP_NAME_PHOEBE,
    SP_NAME_GLACIA,
    SP_NAME_DRAKE,
    SP_NAME_NOLAND,
    SP_NAME_GRETA,
    SP_NAME_TUCKER,
    SP_NAME_LUCY,
    SP_NAME_SPENSER,
    SP_NAME_BRANDON,
    SP_NAME_MAXIE,
    SP_NAME_ARCHIE,
    SP_NAME_JANINE,
    SP_NAME_GREEN,
    // Berry Master's garden (.claude/berry_master/REI_DA_COLHEITA.md)
    SP_NAME_BERRY_MASTER,
    SP_NAME_LAUREL,
    SP_NAME_TILLY,
    SP_NAME_CALYREX,
    SP_NAME_PEONY,
    SP_NAME_PEONIA,
    SP_NAME_KLARA,
    SP_NAME_AVERY,
    SP_NAME_MUSTARD,
    SP_NAME_MOLLY,
    SP_NAME_TOMO,
    SP_NAME_UNKNOWN,
    SP_NAME_BIRCH,
    SP_NAME_MR_FUJI,
    SP_NAME_BUENA,
    SP_NAME_MARY,
    SP_NAME_DAISY,
    SP_NAME_BILL,
    SP_NAME_WARDEN_BAOBA,
    SP_NAME_ZUKI,
    SP_NAME_KUNI,
    SP_NAME_NAOKO,
    SP_NAME_SAYO,
    SP_NAME_MIKI,
    SP_NAME_KIMONO_GIRL,
    SP_NAME_MONICA,
    SP_NAME_TUSCANY,
    SP_NAME_WESLEY,
    SP_NAME_ARTHUR,
    SP_NAME_FRIEDA,
    SP_NAME_SANTOS,
    SP_NAME_SUNNY,
    SP_NAME_IRENE,
    SP_NAME_JENN,
    SP_NAME_KATE,
    SP_NAME_THOM,
    SP_NAME_KAE,
    SP_NAME_EDA,
    SP_NAME_DUFF,
    SP_NAME_MIK,
    SP_NAME_KIA,
    SP_NAME_ANN,
    SP_NAME_ANNE,
    SP_NAME_ANN_AND_ANNE,
    SP_NAME_AMY,
    SP_NAME_AMY_AND_MAY,
    SP_NAME_ED,
    SP_NAME_BARRY,
    SP_NAME_CINDY,
    SP_NAME_BELINDA,
    SP_NAME_SHAUN,
    SP_NAME_SAMUEL,
    SP_NAME_KIPP,
    SP_NAME_JOSH,
    SP_NAME_JAINE,
    SP_NAME_BEN,
    SP_NAME_DIRECTOR,
    SP_NAME_MANAGER,
    SP_NAME_REFEREE,
    SP_NAME_COPYCAT,
    SP_NAME_ROCKET,
    SP_NAME_ATTENDANT,
    SP_NAME_SPECTATORS,
    SP_NAME_AMPHY,
    SP_NAME_SPEARY,
    SP_NAME_RATTEY,
    SP_NAME_STRAWBERRY,
    SP_NAME_ABRA,
    SP_NAME_ALAKAZAM,
    SP_NAME_AUDINO,
    SP_NAME_BAYLEEF,
    SP_NAME_BELLSPROUT,
    SP_NAME_BLISSEY,
    SP_NAME_BUTTERFREE,
    SP_NAME_CHANSEY,
    SP_NAME_CHINCHOU,
    SP_NAME_CLEFAIRY,
    SP_NAME_CORSOLA,
    SP_NAME_DELIBIRD,
    SP_NAME_DEWGONG,
    SP_NAME_DIGLETT,
    SP_NAME_DITTO,
    SP_NAME_DODRIO,
    SP_NAME_DRAGONITE,
    SP_NAME_DRATINI,
    SP_NAME_EEVEE,
    SP_NAME_FARFETCHD,
    SP_NAME_FEAROW,
    SP_NAME_GYARADOS,
    SP_NAME_JIGGLYPUFF,
    SP_NAME_KADABRA,
    SP_NAME_KANGASKHAN,
    SP_NAME_KINGDRA,
    SP_NAME_KINGLER,
    SP_NAME_KRABBY,
    SP_NAME_LICKILICKY,
    SP_NAME_MACHAMP,
    SP_NAME_MACHOKE,
    SP_NAME_MACHOP,
    SP_NAME_MAGMAR,
    SP_NAME_MEOWTH,
    SP_NAME_MILTANK,
    SP_NAME_MUK,
    SP_NAME_MURKROW,
    SP_NAME_NIDORAN,
    SP_NAME_ONIX,
    SP_NAME_PACHIRISU,
    SP_NAME_PERSIAN,
    SP_NAME_PICHU,
    SP_NAME_PIDGEOTTO,
    SP_NAME_POLIWAG,
    SP_NAME_POLIWHIRL,
    SP_NAME_POLIWRATH,
    SP_NAME_QUAGSIRE,
    SP_NAME_RAICHU,
    SP_NAME_RATTATA,
    SP_NAME_SCIZOR,
    SP_NAME_SEEL,
    SP_NAME_SLOWBRO,
    SP_NAME_SLOWKING,
    SP_NAME_SLOWPOKE,
    SP_NAME_STARMIE,
    SP_NAME_STARYU,
    SP_NAME_STEELIX,
    SP_NAME_SWINUB,
    SP_NAME_TENTACRUEL,
    SP_NAME_VICTREEBEL,
    SP_NAME_VULPIX,
    SP_NAME_WOOPER,
    SP_NAME_ZUBAT,
    SP_NAME_SCIENTIST,
    SP_NAME_POLICE,
    SP_NAME_DOVES,
    SP_NAME_ELTON,
    SP_NAME_NEM,
    SP_NAME_BAI,
    SP_NAME_DRAC,
    SP_NAME_TYLARIE,
    SP_NAME_FLOETTE,
    SP_NAME_SNOVER,
    SP_NAME_SABLEYE,
    SP_NAME_BUIZEL,
    SP_NAME_AZUMARILL,
    SP_NAME_MIENSHAO,
    SP_NAME_MIENFOO,
    SP_NAME_SINISTEA,
    SP_NAME_GIBLE,
    SP_NAME_MARACTUS,
    SP_NAME_PHANTUMP,
    SP_NAME_STANTLER,
    SP_NAME_TINKATON,
    SP_NAME_ESPURR,
    SP_NAME_LAMPENT,
    SP_NAME_RHYPERIOR,
    SP_NAME_VULLABY,
    SP_NAME_EXCADRILL,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
