#!/usr/bin/env python3
"""Generate the ROM's versioned documentation QR matrices using only Python 3."""

import argparse
import json
from pathlib import Path
import re
from urllib.parse import urlencode, urlsplit
from zlib import crc32

from qrcodegen import QrCode, QrSegment


ROOT = Path(__file__).resolve().parents[2]
URLS = (
    "https://eemeliri.github.io/soulgold/",
    "https://eemeliri.github.io/soulgold/guides/",
)


def validate_docs_url(url: str, version: str) -> None:
    """Accept only the exact official destinations and the generated version query."""
    path = urlsplit(url).path
    if (path not in ("/soulgold/", "/soulgold/guides/")
            or url != f"https://eemeliri.github.io{path}?{urlencode({'version': version})}"):
        raise ValueError(f"Refusing to generate a QR code for an unofficial docs URL: {url}")


def generate(version_header: Path, output: Path) -> None:
    match = re.search(r'^\s*#define\s+DISPLAY_VERSION\s+("[^"\n]+")',
                      version_header.read_text(), re.MULTILINE)
    if match is None:
        raise ValueError("DISPLAY_VERSION must be a quoted string")
    version = json.loads(match[1])
    lines = [
        "// Generated by tools/docs_qr/generate.py; do not edit.",
        "// One bit per module, most significant bit first, padded per row.",
        "#define DOCS_QR_SIZE 33",
        "static const u8 sDocsQrModules[][DOCS_QR_SIZE][(DOCS_QR_SIZE + 7) / 8] =",
        "{",
    ]
    checksums = []
    for base_url in URLS:
        url = base_url + "?" + urlencode({"version": version})
        validate_docs_url(url, version)
        # Version 4 fits a 123-pixel square at 3 pixels/module, with quiet zone.
        # Reject an oversized URL at build time rather than crop it in the ROM.
        qr = QrCode.encode_segments(QrSegment.make_segments(url), QrCode.Ecc.MEDIUM,
                                    minversion=4, maxversion=4, boostecl=False)
        lines.extend([f"    // {url}", "    {"])
        modules = bytearray()
        for y in range(qr.get_size()):
            row = [sum(int(qr.get_module(x + bit, y)) << (7 - bit)
                       for bit in range(8)) for x in range(0, qr.get_size(), 8)]
            modules.extend(row)
            lines.append("        {" + ", ".join(f"0x{b:02X}" for b in row) + "},")
        lines.append("    },")
        checksums.append(crc32(modules))
    lines.extend(["};", "", "// CRC32 of each packed matrix, including row padding.",
                  "static const u32 sDocsQrChecksums[] =", "{"])
    lines.extend(f"    0x{checksum:08X}," for checksum in checksums)
    lines.extend(["};", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-header", type=Path, default=ROOT / "include/config/version.h")
    parser.add_argument("--output", type=Path, default=ROOT / "src/data/docs_qr.h")
    args = parser.parse_args()
    generate(args.version_header, args.output)
