Gate_KitakamiBorder_MapScripts::
	.byte 0


KitakamiBorderGuard::
	msgbox KitakamiBorderGuard_Text_0, MSGBOX_NPC
	return


KitakamiBorderGuard_Text_0:
	.string "Welcome to Kitakami, traveller!\p"
	.string "You're quite far off from the\n"
	.string "civilization here, but I hope\l"
	.string "you still enjoy the sights.\p"
	.string "If you're planning on visiting the\n"
	.string "Kitakami mountain, be careful of rock\l"
	.string "slides!$"
