# 1 "data/maps/OlivineCity_PortInside/scripts.pory"

# 2 "data/maps/OlivineCity_PortInside/scripts.pory"

# 3 "data/maps/OlivineCity_PortInside/scripts.pory"

# 4 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Movement_OakFixDex:
# 5 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_in_place_up
# 6 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_in_place_up
# 7 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 8 "data/maps/OlivineCity_PortInside/scripts.pory"

# 9 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Movement_PlayerMoveOver:
# 10 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 11 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_left
# 12 "data/maps/OlivineCity_PortInside/scripts.pory"
	face_right
# 13 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 14 "data/maps/OlivineCity_PortInside/scripts.pory"

# 15 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Movement_OakLeave:
# 16 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 17 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 18 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 19 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 20 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 21 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 22 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 23 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 24 "data/maps/OlivineCity_PortInside/scripts.pory"

# 25 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Text_Nationaldex1:
# 26 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Prof.Oak: Hello!\n"
# 27 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "You are starting to have the\l"
# 28 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "attitude of a Champion, {PLAYER}!\p"
# 29 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "It's time for your Pokédex to\n"
# 30 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "match who you are.\p"
# 31 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Let me see your Pokédex for a\n"
# 32 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "second.\p"
# 33 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "I'll upgrade your Pokédex with the\n"
# 34 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "National Mode.$"
# 35 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Text_Nationaldex2:
# 36 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "{PLAYER}'s Pokédex was upgraded\n"
# 37 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "with the National Mode!$"
# 38 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Text_Nationaldex3:
# 39 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Prof.Oak: It won't be easy to\n"
# 40 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "complete the National Pokédex...\p"
# 41 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "However, I'm sure you will make\n"
# 42 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "honest attempt on our behalf!$"
# 43 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivineCity_PortInside_Text_Nationaldex4:
# 44 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Oh, time flies!\p"
# 45 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "I have a radio show to record at\n"
# 46 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Goldenrod Radio Tower.\p"
# 47 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "You must be heading for Sevii.\p"
# 48 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "I hear strong trainers are\n"
# 49 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "gathering there. How exciting!$"
# 50 "data/maps/OlivineCity_PortInside/scripts.pory"

# 51 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_EventScript_CooltrainerF::
# 52 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Text_CooltrainerF, MSGBOX_NPC
# 53 "data/maps/OlivineCity_PortInside/scripts.pory"
	end
# 54 "data/maps/OlivineCity_PortInside/scripts.pory"

# 55 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_EventScript_Fisher1::
# 56 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Text_FishingGuru1, MSGBOX_NPC
# 57 "data/maps/OlivineCity_PortInside/scripts.pory"
	end
# 58 "data/maps/OlivineCity_PortInside/scripts.pory"

# 59 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_EventScript_Fisher2::
# 60 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Text_FishingGuru2, MSGBOX_NPC
# 61 "data/maps/OlivineCity_PortInside/scripts.pory"
	end
# 62 "data/maps/OlivineCity_PortInside/scripts.pory"

# 63 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_EventScript_Youngster::
# 64 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Text_Youngster, MSGBOX_NPC
# 65 "data/maps/OlivineCity_PortInside/scripts.pory"
	end
# 66 "data/maps/OlivineCity_PortInside/scripts.pory"

# 67 "data/maps/OlivineCity_PortInside/scripts.pory"

# 68 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Movement_SailorEnterBoat:
# 69 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_down
# 70 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_down
# 71 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 72 "data/maps/OlivineCity_PortInside/scripts.pory"

# 73 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Movement_PlayerEnterBoat:
# 74 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_down
# 75 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_down
# 76 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_in_place_down
# 77 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 78 "data/maps/OlivineCity_PortInside/scripts.pory"

# 79 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Movement_BoatLeave:
# 80 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_right
# 81 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_right
# 82 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_right
# 83 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_right
# 84 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_right
# 85 "data/maps/OlivineCity_PortInside/scripts.pory"
	step_end
# 86 "data/maps/OlivineCity_PortInside/scripts.pory"

# 87 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_NoPass:
# 88 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "{PLAYER} tried to show the\n"
# 89 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "{STR_VAR_1}…\p"
# 90 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "…But no {STR_VAR_1}!\p"
# 91 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Sorry!\n"
# 92 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "You may board only if you have an\l"
# 93 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "{STR_VAR_1}.$"
# 94 "data/maps/OlivineCity_PortInside/scripts.pory"

# 95 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_SailorGetOnBoard:
# 96 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "We're departing soon.\n"
# 97 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Please get on board.$"
# 98 "data/maps/OlivineCity_PortInside/scripts.pory"

# 99 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_CantBoard:
# 100 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Sorry. You can't board now.$"
# 101 "data/maps/OlivineCity_PortInside/scripts.pory"

# 102 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_WhereSail:
# 103 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Where would you like to sail?$"
# 104 "data/maps/OlivineCity_PortInside/scripts.pory"

# 105 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_AskBoard:
# 106 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Welcome to Fast Ship S.S.Aqua.\p"
# 107 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Will you be boarding today?$"
# 108 "data/maps/OlivineCity_PortInside/scripts.pory"

# 109 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_AskTicket:
# 110 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "May I see your S.S.Ticket?$"
# 111 "data/maps/OlivineCity_PortInside/scripts.pory"

# 112 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_ComeAgain:
# 113 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "We hope to see you again!$"
# 114 "data/maps/OlivineCity_PortInside/scripts.pory"

# 115 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_FlashTicket:
# 116 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "{PLAYER} flashed the S.S.Ticket.\p"
# 117 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "That's it. Thank you!$"
# 118 "data/maps/OlivineCity_PortInside/scripts.pory"

# 119 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_NoTicket:
# 120 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "{PLAYER} tried to show the\n"
# 121 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "S.S.Ticket…\p"
# 122 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "…But no Ticket!\p"
# 123 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Sorry!\n"
# 124 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "You may board only\l"
# 125 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "if you have an S.S.Ticket.$"
# 126 "data/maps/OlivineCity_PortInside/scripts.pory"

# 127 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_FishingGuru1:
# 128 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Mareanie are easy to catch here.\p"
# 129 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "They're kind of rare elsewhere.$"
# 130 "data/maps/OlivineCity_PortInside/scripts.pory"

# 131 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_FishingGuru2:
# 132 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "How many Rods do you have?\p"
# 133 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Different Rods catch different\n"
# 134 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "Pokémon.$"
# 135 "data/maps/OlivineCity_PortInside/scripts.pory"

# 136 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_Youngster:
# 137 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "S.S.Aqua uses jets to skim\n"
# 138 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "over the waves!$"
# 139 "data/maps/OlivineCity_PortInside/scripts.pory"

# 140 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_CooltrainerF:
# 141 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "There are lots of Pokémon in\p"
# 142 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "the world. I wish I could travel...$"
# 143 "data/maps/OlivineCity_PortInside/scripts.pory"

# 144 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePort_Text_SailorBeforeHOF:
# 145 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "We don't want you to fall into the\n"
# 146 "data/maps/OlivineCity_PortInside/scripts.pory"
    .string "sea, so you're not allowed in.$"

OlivineCity_PortInside_MapScripts::
# 150 "data/maps/OlivineCity_PortInside/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION
	.byte 0

OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION:
# 151 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_set FLAG_BADGE08_GET, OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_3
OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_2:
# 154 "data/maps/OlivineCity_PortInside/scripts.pory"
	setflag FLAG_HIDE_BLAINE_OLIVINEPORT
	return

OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_1:
# 152 "data/maps/OlivineCity_PortInside/scripts.pory"
	clearflag FLAG_HIDE_BLAINE_OLIVINEPORT
	return

OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_3:
# 151 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_unset FLAG_CANSAIL_FARAWAYISLAND, OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_1
	goto OlivineCity_PortInside_MapScripts_MAP_SCRIPT_ON_TRANSITION_2


OlivinePort_Sailor::
# 166 "data/maps/OlivineCity_PortInside/scripts.pory"
	lock
# 167 "data/maps/OlivineCity_PortInside/scripts.pory"
	faceplayer
# 170 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_set FLAG_EVENT_NECROZMA_ALTAR_UNLOCKED, OlivinePort_Sailor_2
OlivinePort_Sailor_1:
# 178 "data/maps/OlivineCity_PortInside/scripts.pory"
	checkitem ITEM_SUN_MOON_TICKET
# 179 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq OlivinePort_Sailor_5
OlivinePort_Sailor_4:
# 202 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_unset FLAG_CANSAIL_FARAWAYISLAND, OlivinePort_Sailor_10
# 208 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_8, MSGBOX_YESNO
# 211 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, NO
	goto_if_eq OlivinePort_Sailor_16
# 216 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto OlivinePort_EventScript_SailFaraway
	return

OlivinePort_Sailor_2:
# 171 "data/maps/OlivineCity_PortInside/scripts.pory"
	checkitem ITEM_SUN_MOON_TICKET
# 172 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq OlivinePort_Sailor_7
	goto OlivinePort_Sailor_1

OlivinePort_Sailor_5:
# 180 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_set FLAG_CANSAIL_FARAWAYISLAND, OlivinePort_Sailor_13
# 193 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_6, MSGBOX_YESNO
# 195 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, NO
	goto_if_eq OlivinePort_Sailor_19
# 200 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto OlivinePort_EventScript_SailAltar
	goto OlivinePort_Sailor_4

OlivinePort_Sailor_7:
# 173 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_0
# 175 "data/maps/OlivineCity_PortInside/scripts.pory"
	giveitem ITEM_SUN_MOON_TICKET
	goto OlivinePort_Sailor_1

OlivinePort_Sailor_10:
# 203 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_7
# 205 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePort_Sailor_13:
# 181 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_1
# 182 "data/maps/OlivineCity_PortInside/scripts.pory"
	dynmultichoice 0, 0, FALSE, 3, 0, DYN_MULTICHOICE_CB_NONE, OlivinePort_Sailor_Text_2, OlivinePort_Sailor_Text_3, OlivinePort_Sailor_Text_4
# 183 "data/maps/OlivineCity_PortInside/scripts.pory"
	switch VAR_RESULT
# 184 "data/maps/OlivineCity_PortInside/scripts.pory"
	case 0, OlivinePort_Sailor_23
# 186 "data/maps/OlivineCity_PortInside/scripts.pory"
	case 1, OlivinePort_Sailor_24
OlivinePort_Sailor_21:
# 189 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_5
# 190 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePort_Sailor_16:
# 212 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_9
# 213 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePort_Sailor_19:
# 196 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_Sailor_Text_5
# 197 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePort_Sailor_23:
# 185 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto OlivinePort_EventScript_SailAltar
	goto OlivinePort_Sailor_21

OlivinePort_Sailor_24:
# 187 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto OlivinePort_EventScript_SailFaraway
	goto OlivinePort_Sailor_21


OlivinePort_EventScript_SailAltar::
# 220 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_EventScript_SailAltar_Text_0
# 225 "data/maps/OlivineCity_PortInside/scripts.pory"
	closemessage
# 227 "data/maps/OlivineCity_PortInside/scripts.pory"
	warp MAP_SUN_MOON_ALTAR, 14, 27
# 228 "data/maps/OlivineCity_PortInside/scripts.pory"
	waitstate
# 229 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end


OlivinePort_EventScript_SailFaraway::
# 234 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePort_EventScript_SailFaraway_Text_0
# 238 "data/maps/OlivineCity_PortInside/scripts.pory"
	closemessage
# 239 "data/maps/OlivineCity_PortInside/scripts.pory"
	warp MAP_FARAWAY_ISLAND_OUTSIDE, 13, 38
# 240 "data/maps/OlivineCity_PortInside/scripts.pory"
	waitstate
# 241 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end


OlivinePortBlaine::
# 246 "data/maps/OlivineCity_PortInside/scripts.pory"
	lock
# 247 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_set FLAG_CANSAIL_FARAWAYISLAND, OlivinePortBlaine_2
# 253 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_unset FLAG_TEMP_5, OlivinePortBlaine_5
OlivinePortBlaine_4:
# 289 "data/maps/OlivineCity_PortInside/scripts.pory"
	goto_if_set FLAG_TEMP_5, OlivinePortBlaine_8
OlivinePortBlaine_7:
# 305 "data/maps/OlivineCity_PortInside/scripts.pory"
	playbgm MUS_RG_ENCOUNTER_GYM_LEADER, FALSE
# 306 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_9
# 308 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_10
# 309 "data/maps/OlivineCity_PortInside/scripts.pory"
	trainerbattle_no_intro TRAINER_BLAINE_OLIVINE, OlivinePortBlaine_Text_11
# 310 "data/maps/OlivineCity_PortInside/scripts.pory"
	createfieldmugshot MUGSHOT_BLAINE
# 311 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_12
# 328 "data/maps/OlivineCity_PortInside/scripts.pory"
	closemessage
# 329 "data/maps/OlivineCity_PortInside/scripts.pory"
	moveobjecttocoords LOCALID_OLI_BLAINE, 8, 16, DIR_SOUTH
# 330 "data/maps/OlivineCity_PortInside/scripts.pory"
	waitmovement 0
# 331 "data/maps/OlivineCity_PortInside/scripts.pory"
	turnobject LOCALID_PLAYER, DIR_SOUTH
# 332 "data/maps/OlivineCity_PortInside/scripts.pory"
	delay 60
# 333 "data/maps/OlivineCity_PortInside/scripts.pory"
	moveobjecttocoords LOCALID_OLI_BLAINE, 8, 12, DIR_NORTH
# 334 "data/maps/OlivineCity_PortInside/scripts.pory"
	waitmovement 0
# 335 "data/maps/OlivineCity_PortInside/scripts.pory"
	turnobject LOCALID_PLAYER, DIR_EAST
# 336 "data/maps/OlivineCity_PortInside/scripts.pory"
	turnobject LOCALID_OLI_BLAINE, DIR_WEST
# 337 "data/maps/OlivineCity_PortInside/scripts.pory"
	createfieldmugshot MUGSHOT_BLAINE
# 338 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_13
# 339 "data/maps/OlivineCity_PortInside/scripts.pory"
	closemessage
# 340 "data/maps/OlivineCity_PortInside/scripts.pory"
	applymovement LOCALID_OLI_BLAINE, OlivinePortBlaine_Movement_0
# 341 "data/maps/OlivineCity_PortInside/scripts.pory"
	waitmovement
# 342 "data/maps/OlivineCity_PortInside/scripts.pory"
	playse SE_EXIT
# 343 "data/maps/OlivineCity_PortInside/scripts.pory"
	removeobject LOCALID_OLI_BLAINE
# 344 "data/maps/OlivineCity_PortInside/scripts.pory"
	setflag FLAG_CANSAIL_FARAWAYISLAND
# 345 "data/maps/OlivineCity_PortInside/scripts.pory"
	setflag FLAG_HIDE_BLAINE_OLIVINEPORT
# 346 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePortBlaine_2:
# 248 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_0
# 250 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePortBlaine_5:
# 254 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_1
# 256 "data/maps/OlivineCity_PortInside/scripts.pory"
	faceplayer
# 257 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_2
# 268 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_3, MSGBOX_YESNO
# 269 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq OlivinePortBlaine_11
# 274 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_5, MSGBOX_YESNO
# 280 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, NO
	goto_if_eq OlivinePortBlaine_15
	goto OlivinePortBlaine_4

OlivinePortBlaine_8:
# 290 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_7, MSGBOX_YESNO
# 295 "data/maps/OlivineCity_PortInside/scripts.pory"
	compare VAR_RESULT, NO
	goto_if_eq OlivinePortBlaine_13
	goto OlivinePortBlaine_7

OlivinePortBlaine_11:
# 270 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_4
# 271 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePortBlaine_13:
# 296 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_8
# 301 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end

OlivinePortBlaine_15:
# 281 "data/maps/OlivineCity_PortInside/scripts.pory"
	msgbox OlivinePortBlaine_Text_6
# 284 "data/maps/OlivineCity_PortInside/scripts.pory"
	setflag FLAG_TEMP_5
# 285 "data/maps/OlivineCity_PortInside/scripts.pory"
	release
	end


# 340 "data/maps/OlivineCity_PortInside/scripts.pory"
OlivinePortBlaine_Movement_0:
# 340 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 340 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
# 340 "data/maps/OlivineCity_PortInside/scripts.pory"
	walk_up
	step_end

OlivinePort_Sailor_Text_0:
# 173 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Oh! A man in a trench coat left\n"
	.string "this here for you.$"

OlivinePort_Sailor_Text_1:
# 181 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Where would you like to sail?$"

OlivinePort_Sailor_Text_2:
# 182 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Sun & Moon Altar$"

OlivinePort_Sailor_Text_3:
# 182 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Faraway Island$"

OlivinePort_Sailor_Text_4:
# 182 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Cancel$"

OlivinePort_Sailor_Text_5:
# 189 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "We hope to see you again!$"

OlivinePort_Sailor_Text_6:
# 193 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Ah, the Sun & Moon Ticket!\n"
	.string "Shall we set sail for the altar?$"

OlivinePort_Sailor_Text_7:
# 203 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Sorry, but the ship is not going to\n"
	.string "leave anywhere anytime soon.$"

OlivinePort_Sailor_Text_8:
# 208 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "I was told to sail you to this\n"
	.string "oddly specific location. Do you\l"
	.string "want to go now?$"

OlivinePort_Sailor_Text_9:
# 212 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Oh, alright...$"

OlivinePort_EventScript_SailAltar_Text_0:
# 220 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "{PLAYER} flashed the\n"
	.string "Sun & Moon Ticket.\p"
	.string "Anchors aweigh! Next stop,\n"
	.string "the Sun and Moon Altar!$"

OlivinePort_EventScript_SailFaraway_Text_0:
# 234 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Then let's do it!\p"
	.string "Anchors aweigh! We're setting sail\n"
	.string "to the unknown!$"

OlivinePortBlaine_Text_0:
# 248 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: I let the sailor know about the\n"
	.string "island.$"

OlivinePortBlaine_Text_1:
# 254 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "???: Ahh... Nothing quite like \n"
	.string "a refreshing Soda Pop!$"

OlivinePortBlaine_Text_2:
# 257 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Oh! Are those all 8 badges of Johto?\p"
	.string "You must be quite a trainer to have\n"
	.string "achieved such a feat!\p"
	.string "My name is Blaine. I am a Gym Leader in\n"
	.string "another region.\p"
	.string "Blaine: Ooh! I have an idea!\p"
	.string "Quiz time!$"

OlivinePortBlaine_Text_3:
# 268 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: Are you afraid of the unknown?$"

OlivinePortBlaine_Text_4:
# 270 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Oh... Wrong Answer!$"

OlivinePortBlaine_Text_5:
# 274 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: Good!\p"
	.string "Next question!\p"
	.string "Do you think you could beat me in\n"
	.string "a Pokémon battle?$"

OlivinePortBlaine_Text_6:
# 281 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: I respect the honesty, but you\n"
	.string "should have a bit more confidence\l"
	.string "in yourself!$"

OlivinePortBlaine_Text_7:
# 290 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Changed your mind about the\n"
	.string "last question?\p"
	.string "Do you think you could beat me in\n"
	.string "a Pokémon battle?$"

OlivinePortBlaine_Text_8:
# 296 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: Still not confident enough?\n"
	.string "Well I can't blame you. \p"
	.string "After all, I am quite the fiery soul!\n"
	.string "Ho ho ho!$"

OlivinePortBlaine_Text_9:
# 306 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: Such a bold statement! \n"
	.string "I shall put that to the test right here!$"

OlivinePortBlaine_Text_10:
# 308 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Hope you brought a Burn Heal!$"

OlivinePortBlaine_Text_11:
# 309 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Wowzers! You scorched me!$"

OlivinePortBlaine_Text_12:
# 311 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Blaine: Yowch! I got burned!\n"
	.string "You're the real deal!\p"
	.string "Here's the thing. I was visiting\n"
	.string "Johto to check up on my old friend\l"
	.string "Oak, who is currently here. \p"
	.string "I found this old map of an island\n"
	.string "we visited long, long ago.\p"
	.string "I don't think anyone has visited it\n"
	.string "since then. \p"
	.string "I will tell the sailor about the island.\n"
	.string "Speak to him if you wish to visit it.\p"
	.string "You might find some rare Pokémon there!$"

OlivinePortBlaine_Text_13:
# 338 "data/maps/OlivineCity_PortInside/scripts.pory"
	.string "Good luck out there!$"
